# optimiser_agent.py
import os
from pathlib import Path
from datetime import datetime
import pandas as pd

from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage
from langchain_core.tools import tool

import z_calculator_latest



@tool
def run_optimisation(
    SPEED: str = "ECON",
    DWT_MULTIPLIER: float = 1.0,
    SPEED_MULTIPLIER: float = 1.0,
    VLSF_BUFFER_PCT: float = 0.0,
    MGO_BUFFER_PCT: float = 0.0,
) -> dict:
    """
    Run fleet optimisation using latest calculator logic.
    Uses get_distance_nm_safe internally via z_calculator_latest.calculate().
    "Base case: \n"
    " -  Use default values.\n"
    "ML case: \n"
    " -  ML = True.\n"
    "Scenarios case: \n"
    " -  SPEED = ['ECON' / 'WARRANTED]).\n"
    " -  DWT_MULTIPLIER = float value of 0.9 if u want a buffer of 10%, etc.\n"
    " -  SPEED_MULTIPLIER = float value of 0.9 if u want a speed reduction of 10%, etc.\n"
    " -  LOAD_PORT_DELAY = constant for delays in load port in days.\n"
    " -  DISCHARGE_PORT_DELAY = constant for delays in discharge port in days.\n"
    " -  VLSF_BUFFER = float value of 0.9 if u want a buffer of 10%, etc.\n"
    " -  MGO_BUFFER = float value of 0.9 if u want a buffer of 10%, etc.\n"
    " -  BUNKER_COST = new bunker port cost (constant to be applied to all ports).\n"
    """
    # Run calculator
    z_calculator_latest.calculate(
        ML=False,
        PRUNE=True,
        SPEED=SPEED,
        DWT_MULTIPLIER=DWT_MULTIPLIER,
        SPEED_MULTIPLIER=SPEED_MULTIPLIER,
        LOAD_PORT_DELAY=0.0,
        DISCHARGE_PORT_DELAY=0.0,
        VLSF_BUFFER_PCT=VLSF_BUFFER_PCT,
        MGO_BUFFER_PCT=MGO_BUFFER_PCT,
        BUNKER_PORT_COST=5000.0,
    )

    # Read outputs from the calculator's directory
    run_dir = Path(z_calculator_latest.__file__).resolve().parent
    out_file = run_dir / "fleet_assignment_base.csv"
    df = pd.read_csv(out_file)

    portfolio_value = float(df["assigned_value"].sum()) if "assigned_value" in df.columns else None

    return {
        "portfolio_value_usd": portfolio_value,
        "rows": int(len(df)),
        "run_dir": str(run_dir),
        "output_file": str(out_file),
    }




@tool
def list_run_outputs(run_dir: str) -> dict:
    """
    List all CSV output files generated by an optimisation run.

    This tool is used by the agent to discover which result files
    (e.g. assignment tables or pairwise calculations) are available
    for a given optimisation run.

    Parameters
    ----------
    run_dir : str
        Path to the optimisation run directory.

    Returns
    -------
    dict
        {
            "run_dir": str,        # resolved run directory path
            "csv_files": list[str] # names of CSV files in the directory
        }
    """
    p = Path(run_dir)
    files = sorted([f.name for f in p.glob("*.csv")])
    return {"run_dir": str(p), "csv_files": files}



@tool
def load_fleet_assignment(run_dir: str, ml: bool = False) -> dict:
    """
    Load and summarize the fleet assignment results for an optimisation run.

    This tool reads the fleet assignment CSV and returns a compact,
    model-friendly summary that the agent can use to explain
    voyage recommendations, TCEs, and profits.

    Parameters
    ----------
    run_dir : str
        Path to the optimisation run directory.
    ml : bool
        If True, load the ML-based assignment (fleet_assignment_ml.csv).
        If False, load the base case assignment (fleet_assignment_base.csv).

    Returns
    -------
    dict
        {
            "file": str,               # path to the CSV file
            "rows": int,               # number of assignments
            "total_score": float,      # sum of assigned_value (USD)
            "assignments": list[dict]  # per-vessel assignment summary
        }
    """
    p = Path(run_dir) / ("fleet_assignment_ml.csv" if ml else "fleet_assignment_base.csv")
    df = pd.read_csv(p)

    # small payload for the model
    cols = [
        "cargo_id","vessel_id","vessel_name","src_vessel","src_cargo",
        "assigned_value","tce_usd_per_day","total_days","bunker_location"
    ]
    cols = [c for c in cols if c in df.columns]
    return {
        "file": str(p),
        "rows": int(len(df)),
        "total_score": float(df["assigned_value"].sum()) if "assigned_value" in df.columns else None,
        "assignments": df[cols].sort_values("assigned_value", ascending=False).to_dict(orient="records"),
    }



@tool
def load_pair_row(run_dir: str, vessel_id: str, cargo_id: str, ml: bool = False) -> dict:
    """
    Load detailed calculation results for a specific vessel-cargo pair.

    This tool allows the agent to explain *why* a particular voyage
    was chosen (or not chosen) by exposing the full cost, revenue,
    fuel, and timing breakdown for that pair.

    Parameters
    ----------
    run_dir : str
        Path to the optimisation run directory.
    vessel_id : str
        Vessel identifier.
    cargo_id : str
        Cargo identifier.
    ml : bool
        If True, read from ML_cases.csv.
        If False, read from base_cases.csv.

    Returns
    -------
    dict
        {
            "file": str,          # path to the CSV file
            "found": bool,        # whether the pair exists
            "row": dict | None    # full calculation row if found
        }
    """
    p = Path(run_dir) / ("ML_cases.csv" if ml else "base_cases.csv")
    df = pd.read_csv(p)

    m = (df["vessel_id"].astype(str) == str(vessel_id)) & (df["cargo_id"].astype(str) == str(cargo_id))
    if not m.any():
        return {"file": str(p), "found": False}

    row = df.loc[m].iloc[0].to_dict()
    return {"file": str(p), "found": True, "row": row}



optimiser_tools = [
    run_optimisation,
    list_run_outputs,
    load_fleet_assignment,
    load_pair_row
]

optimiser_model = ChatOpenAI(model="gpt-4o").bind_tools(optimiser_tools)


def optimiser_agent(state: dict) -> dict:
    system = SystemMessage(
        content=(
            "You are an optimiser agent working as a Cargill dry bulk trader.\n"
            "Use u can optimise for : \n"
            " - Base case: \n"
            " - ML case: \n"
            " - Scenarios case: \n"
            "Base case is to optimise to deliver all cargill cargoes, with all cargill and market vessels available to use\n"
            "You can use math agent's tools to list all vessels and cargoes"
            "If data is missing, ask the user."
        )
    )
    resp = optimiser_model.invoke([system] + state["messages"])
    return {"messages": [resp]}
